[package]
name = "rust_zkp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.3"
serde_json = "1.0"
ark-bls12-381 = "0.4.0"
ark-groth16 = "0.3.0"
ark-relations = "0.3.0"
ark-std = "0.4.0"
ark-ff = "0.3.0"
ark-bn254 = "0.3.0"
ark-serialize = "^0.3.0"
console_error_panic_hook = "0.1.7"
ark-ec = "0.4.0"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }


[dependencies.web-sys]
version = "0.3"
features = ["console"]

[profile.release]
lto = true
codegen-units = 1
debug = true  
